# Generated by Django 3.2.20 on 2023-07-26 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Ягода')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='название торта')),
                ('description', models.TextField(blank=True, verbose_name='описание торта')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение торта')),
                ('default', models.BooleanField(default=False, verbose_name='торт в ассортименте')),
                ('berries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakes', to='cake_shop.berry', verbose_name='ягоды')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('address', models.TextField(help_text='ул. Подольских курсантов д.5 кв.4', verbose_name='Адрес квартиры')),
            ],
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Декор')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество слоев')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий к заказу')),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма заказа')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('delivery_date', models.DateField(blank=True, verbose_name='время создания')),
                ('delivery_time', models.CharField(blank=True, choices=[('01', '08:00-10:00'), ('02', '10:00-12:00'), ('03', '12:00-14:00'), ('04', '14:00-16:00'), ('05', '16:00-18:00'), ('06', '18:00-20:00'), ('07', '20:00-22:00')], max_length=2)),
                ('delivery_type', models.CharField(blank=True, choices=[('01', 'Курьером'), ('02', 'Самовывоз')], max_length=2)),
                ('order_status', models.CharField(choices=[('01', 'Оформлен'), ('02', 'В доставке'), ('03', 'Доставлен')], default='01', max_length=2)),
                ('urgency', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=32, verbose_name='Форма коржа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Топпинг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество тортов')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий к торту')),
                ('cake_text', models.TextField(blank=True, verbose_name='текст на торте')),
                ('cake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_cakes', to='cake_shop.cake', verbose_name='торты')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_cakes', to='cake_shop.order', verbose_name='заказы')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cakes',
            field=models.ManyToManyField(related_name='orders', through='cake_shop.OrderedCake', to='cake_shop.Cake', verbose_name='торты'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cake_shop.client', verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='cake',
            name='decor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakes', to='cake_shop.decor', verbose_name='декор'),
        ),
        migrations.AddField(
            model_name='cake',
            name='layers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakes', to='cake_shop.layer', verbose_name='слои'),
        ),
        migrations.AddField(
            model_name='cake',
            name='shape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakes', to='cake_shop.shape', verbose_name='форма'),
        ),
        migrations.AddField(
            model_name='cake',
            name='toppings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakes', to='cake_shop.topping', verbose_name='топинги'),
        ),
    ]
