# Generated by Django 3.2.20 on 2023-07-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='quantity',
        ),
        migrations.AddField(
            model_name='layer',
            name='title',
            field=models.CharField(blank=True, max_length=32, verbose_name='Количество слоев'),
        ),
    ]
