# Generated by Django 3.2.20 on 2023-07-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop', '0002_auto_20230726_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shape',
            old_name='shape',
            new_name='title',
        ),
    ]
