# Generated by Django 3.2.20 on 2023-07-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop', '0003_rename_shape_shape_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='category',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
