# Generated by Django 3.2.20 on 2023-07-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop', '0004_cake_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='category',
            field=models.CharField(blank=True, choices=[('01', 'На день рождения'), ('02', 'На свадьбу'), ('03', 'На чаепитие')], max_length=2),
        ),
    ]
