# Generated by Django 3.2.19 on 2023-08-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop', '0007_alter_order_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
    ]
