# Generated by Django 3.2.19 on 2023-07-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop', '0006_update_client_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма заказа'),
        ),
    ]
