# Generated by Django 3.2.20 on 2023-08-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop', '0007_client_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, verbose_name='дата доставки'),
        ),
    ]
