# Generated by Django 3.2.20 on 2023-08-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop', '0008_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, choices=[('01', '08:00-10:00'), ('02', '10:00-12:00'), ('03', '12:00-14:00'), ('04', '14:00-16:00'), ('05', '16:00-18:00'), ('06', '18:00-20:00'), ('07', '20:00-22:00')], max_length=2, verbose_name='время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('01', 'Курьером'), ('02', 'Самовывоз')], max_length=2, verbose_name='вид доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('01', 'Оформлен'), ('02', 'В доставке'), ('03', 'Доставлен')], default='01', max_length=2, verbose_name='статус заказа'),
        ),
    ]
